### ISSUE TITLE
Architecture question

### ISSUE THREAD

**Issue by espositofulvio** [RobertoPrevato/rodi#2]
Hi Roberto,
I recently become interested in dependency injection and was investigating a few options for python. I first found [Lagom](https://github.com/meadsteve/lagom) and then found rodi. I can see quite the similarities between the two projects if you neglect syntax differences but there's a more fundamental difference in design. Lagom use the container class also for service resolution, while you have a two step process, container configuration which in turns builds a provider (the services) for service resolution. One thing that comes to mind is that, according to documentation, Lagom is only based on types, while rodi supports also the convention over configuration style which might account for the difference. Are there any reasons rodi split the container in two? (I know you took inspiration for .NET, but I don't know very well that land to say if the split is there as well).
Thanks

**Comment by RobertoPrevato** [comment]
Hi Fulvio,
Thanks for your interest in my library. The reason why I split the container in two, is because this way I can do only once slow operations, such as detecting circular dependencies in service resolution, detect missing services, and inspection of `__init__` methods (code reflection is generally slow).

After these inspections are executed, functions that activate services are generated dynamically. When a service is activated, in other words when an instance of a class is created, there is no inspection of method signatures happening, no further validation.

Some things are different than in the .NET implementation. For example, in the .NET implementation the validation of services happens the first time a service is activated. Meaning that, if the DI is not well configured and a service is missing, this becomes evident the first time that service is requested (e.g. in ASP.NET Core, when handling web requests). I preferred a system that failed immediately, to be more user-friendly for developers. If a service cannot be activated because one of its dependencies is not registered, the call to build the services raises exception immediately.
